### ISSUE TITLE
v1.0

### ISSUE THREAD

**Issue by MKonovalow** [SPC-project/Regular-Divider#1]
## Основные задачи:
- [x] Сохранение составных фигур
- [x] Проверка на перекрытие примитивов (или их воздушных оболочек)
- [x] "Сохранить как"
- [x] Экспорт фигур (не разбиения) - на случай, если кто-то захочет начать с заготовки или перенести куда фигуру
- [x] Ставить ограничения на диалог редактирования для примитивов с занятыми смежными сторонами
- [x] Пункт "Очистить" в контекстное меню
- [x] Горячие клавиши:
  - Добавить фигуру
  - Сохранить
  - Закрыть приложение
- [ ] Undo/Redo #6 
## Ошибки:
- [x] Нужно выставить ограничение на смещение в expand-диалоге, а то можно выставить такую начальную позицию, что они окажутся разъедененными
- [x] Нижняя граница зафиксированная на отметке "0" в том же диалоге может привести к тому, что собьется выравнивание шага. Да и толку в нем теперь, когда можно двигать рабочую область, нет 
- [ ] Сейчас с боку может быть только один достроенный элемент (более новый затирает более предыдущий) - _пока просто вывожу предупреждение об этом_.
- [x] Удаление элемента не обновляет холст
- [x] Редактирование создает новый элемент, вместо того чтобы изменять старый
- [x] Нужно проверять ширину и высоту генерируемого прямоугольника на неравенство нулю
## Опционально:
- [ ] Если строится новый примитв, проверять не стыкуется он с существующими и если да - предлагать соединить их представления
- [x] Пересмотреть логику создания новых узлов: сейчас sewing_nodes может содержать копии, так как узел создается сначала для нижнего угла, а на следующем шаге - для верхнего
- [x] Выводить сообщение в строку состояний о наличии более свежей версии
- [x] "Выйти" в меню
- [ ] Сделать VERSION не константой в main, но читать из локального Changelog.txt

**Comment by major-kolz** [comment]
Проверка на перекрытие вроде как решена за счет нового алгоритма.
См. Combiner.py

**Comment by major-kolz** [comment]
Похоже, использую систему issues не совсем правильно
