### ISSUE TITLE
Автоматическое тестирование

### ISSUE THREAD

**Issue by MKonovalow** [SPC-project/Regular-Divider#2]
Функциональные тесты: генерируем сетку определенной формы, сохраняем, сверяем полученный файл с сохраненным "эталонным" результатом.
![p60530-084258](https://cloud.githubusercontent.com/assets/14095847/15640653/efaaac22-2642-11e6-99b6-3e78247d2100.jpeg)

**Comment by MKonovalow** [comment]
Безпрерывная интеграция. Пусть travis эти тесты при каждом пуше прогоняет

**Comment by major-kolz** [comment]
Выполненно
