### ISSUE TITLE
Разбиение "избыточной сеткой"

### ISSUE THREAD

**Issue by MKonovalow** [SPC-project/Regular-Divider#3]
**Сработает только для фигур с гомогенной сеткой**

*Гомогенная: все ячеки между собой равны*

Находим верхнюю левую точку составной фигуры и нижнюю правую. Запускаем цикл по всем узлам прямоугольника на этих точках образованного (его разбиение и есть "избыточная сетка"). 

После чего проверяем, принадлежит ли точка какому-либо примитиву и если да - записываем координаты, увеличиваем счетчик узлов и  переходим к следующему узлу. Узлы супер-прямоугольника вне примитивов просто пропускаются. Связывание узлов в треугольники происходит по тому же принципу, просто проверяется "существование" не одного узла, а четверки

**Comment by major-kolz** [comment]
Реализован другой подход: каждый примитив разбивается отдельно, после чего удаляются все дублирующие узлы и их имена исправляются
